[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.121.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_EXTENDED = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.121.2"
HUGO_ENV = "production"
HUGO_EXTENDED = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.121.2"
HUGO_EXTENDED = "true"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.121.2"
HUGO_EXTENDED = "true"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[security]
  [security.gotemplates]
    allowActionJSTmpl = true

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/:splat" # adding a placeholder to keep the same structure
status = 200
